# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."stremio-server-stremio" = {
    image = "tsaridas/stremio-docker:latest";
    environment = {
      "AUTO_SERVER_URL" = "1";
      "NO_CORS" = "1";
    };
    volumes = [
      "/home/mateusp/stremio-docker/stremio-data:/root/.stremio-server:rw"
    ];
    ports = [
      "12345:8080/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=stremio"
      "--network=stremio-server_default"
    ];
  };
  systemd.services."docker-stremio-server-stremio" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-stremio-server_default.service"
    ];
    requires = [
      "docker-network-stremio-server_default.service"
    ];
    partOf = [
      "docker-compose-stremio-server-root.target"
    ];
    wantedBy = [
      "docker-compose-stremio-server-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-stremio-server_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f stremio-server_default";
    };
    script = ''
      docker network inspect stremio-server_default || docker network create stremio-server_default
    '';
    partOf = [ "docker-compose-stremio-server-root.target" ];
    wantedBy = [ "docker-compose-stremio-server-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-stremio-server-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
