{ pkgs, lib, secrets, ... }:

let
  # Define the script directly in Nix
  restartIfIdleScript = pkgs.writeShellScript "restart_if_idle.sh" ''
    # URL to check
    URL="http://localhost:11470/stats.json"

    # Process name
    PROCESS_NAME="node server.js"

    # Function to restart the process
    restart_process() {
        echo "$1" > /proc/1/fd/1 2>/proc/1/fd/2
        pkill -f "$PROCESS_NAME"
        nohup $PROCESS_NAME > /proc/1/fd/1 2>/proc/1/fd/2 &
        echo "Process restarted." > /proc/1/fd/1 2>/proc/1/fd/2
    }

    # Check if force restart is requested
    if [ "$1" = "--force" ]; then
        restart_process "Force restart requested. Restarting the process..."
        exit 0
    fi

    # Make the HTTP call
    # Note: Using 'curl' - ensure it is available in the container image
    response=$(curl -s "$URL")
    curl_exit_status=$?

    # Check if curl failed (non-zero exit status)
    if [ $curl_exit_status -ne 0 ]; then
        restart_process "Curl failed with connection error. Restarting the process..."
    # Check if the response is an empty JSON object
    elif [ "$response" = "{}" ]; then
        restart_process "Empty JSON response detected. Restarting the process..."
    else
        echo "Non-empty JSON response. No action needed." > /proc/1/fd/1 2>/proc/1/fd/2
    fi
  '';
in
{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."stremio-server-stremio" = {
    image = "tsaridas/stremio-docker:latest";
    environment = {
      "AUTO_SERVER_URL" = "1";
      "NO_CORS" = "1";
    };
    volumes = [
      "/home/mateusp/nix-config/modules/docker-containers/stremio-data:/root/.stremio-server:rw"
      # Mount the Nix-generated script into the container
      "${restartIfIdleScript}:/restart_if_idle.sh:ro"
    ];
    ports = [
      "12345:8080/tcp"
      "11470:11470"
      "12470:12470"
    ];
    log-driver = "journald";
    extraOptions = [
      "--device=/dev/dri:/dev/dri:rwm"
      "--network-alias=stremio"
      "--network=stremio-server_default"
      # Healthcheck implementation via Docker flags
      "--health-cmd=/restart_if_idle.sh"
      "--health-interval=1h0m0s"
      "--health-start-period=1h0m0s"
      "--health-retries=1"
      # VITAL FOR AV1 SOFTWARE DECODING:
      "--cpu-shares=2048"          # Give it higher priority than other containers
      "--cpus=6"                   # Allow it to burst across most of your 8 logical cores
      "--shm-size=2gb"             # AV1 needs larger memory buffers for the "probe" process
      "--memory=4g"                # Prevents OOM (Out of Memory) crashes during 10-bit AV1 parsing
    ];
  };

  systemd.services."docker-stremio-server-stremio" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-stremio-server_default.service"
    ];
    requires = [
      "docker-network-stremio-server_default.service"
    ];
    partOf = [
      "docker-compose-stremio-server-root.target"
    ];
    wantedBy = [
      "docker-compose-stremio-server-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-stremio-server_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f stremio-server_default";
    };
    script = ''
      docker network inspect stremio-server_default || docker network create stremio-server_default
    '';
    partOf = [ "docker-compose-stremio-server-root.target" ];
    wantedBy = [ "docker-compose-stremio-server-root.target" ];
  };

  # Root service
  systemd.targets."docker-compose-stremio-server-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };

  # # services.openvpn.servers = {
  # #   tecnicoVPN = { 
  # #     config = "${secrets.immich.postgres.password}";
  # #   };
  # # };
}