name: Delete Old Workflows

on:
  schedule:
    - cron: '0 0 * * *'  # Specify your own schedule
  workflow_dispatch:    # Allow manual triggering
  
jobs:
  delete-old-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5 
      - uses: yanovation/delete-old-actions@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          days-ago: 30
