name: Deploy NixOS Systems

on:
  push:
    branches: [ main ]  # Trigger on pushes to main branch
  workflow_run:
    workflows: ["Update Nix Flake"]
    types:
      - completed
  workflow_dispatch:    # Allow manual triggering


concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v5.0.0 
      # # - name: Free Disk Space (Ubuntu)
      # #   uses: jlumbroso/free-disk-space@v1.3.1
      # #   with:
      # #     docker-images: false
      - uses: DeterminateSystems/flake-checker-action@main
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/flakehub-cache-action@v2
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan omi.footvaalvica.com raidou.rnl.tecnico.ulisboa.pt >> ~/.ssh/known_hosts
      - uses: actions/checkout@master
      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.3.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      
      - name: Deploy systems
        run: |
          nix run github:serokell/deploy-rs -- -s .
